CREATE DATABASE IF NOT EXISTS db1 DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

CREATE TABLE `db1`.`user` (
	`id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`name` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '姓名',
	`age` tinyint(4) DEFAULT NULL COMMENT '年龄',
	`birthday` date DEFAULT NULL COMMENT '生日',
	`sys_create_date` datetime DEFAULT NULL COMMENT '创建日期',
	PRIMARY KEY (`id`)
) ENGINE=`InnoDB` AUTO_INCREMENT=0 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ROW_FORMAT=DYNAMIC COMMENT='用户表' CHECKSUM=0 DELAY_KEY_WRITE=0;

